### ISSUE TITLE
Create a github action to redeploy the bot after a commit to master

### ISSUE THREAD

**Issue by nikosbosse** [nikosbosse/Metaculus-Twitter-bot#11]
The deploy.sh script needs to be triggered and the credentials stored safely

**Comment by seabbs** [comment]
Could also just switch the bot to run using GitHub actions only and not use Google cloud functions.

**Comment by nikosbosse** [comment]
Ha very good point. It seems like gh action quotas are more generous than google cloud functions. Now I just need to learn how to create gh action scripts...

**Comment by seabbs** [comment]
I usually just role my face on the keyboard until they do what I want.

**Comment by nikosbosse** [comment]
> I usually just role my face on the keyboard until they do what I want.

--> me, programming...

**Comment by dbaynard** [comment]
Hello, I’m happy to help out with a migration to github actions. I’ve moved AWS deployments (including a python lambda) to github actions before, but not GCP. Github actions can be a little flaky, so you might want to stick with GCP for the actual bot.

If you just want to handle _code_ changes (not dependencies) then something like this should get your started. You’ll need the add the secrets `GCP_workload_identity_provider` and `GCP_service_account` (or use one of the other authentication methods). See [google-github-actions/setup-gcloud: A GitHub Action for configuring the Google Cloud SDK. The Google Cloud SDK includes both the gcloud and gsutil binaries.](https://github.com/google-github-actions/setup-gcloud#usage)

Edit: this file would be something like `.github/workflows/deploy.yml`

```yaml
name: Deploy GCP Function
on:
  push:
    branches:
    - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  # Cancel ongoing build when redeploying
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    # Enable write permission on id-token — I'd have to dig in to the
    # auth action code to work out why this is needed.
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      # https://github.com/google-github-actions/auth
      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@d16fd896f76605863c491de993d3e5d5cf4f68f8
        with:
          workload_identity_provider: ${{ secrets.GCP_workload_identity_provider }}
          service_account: ${{ secrets.GCP_service_account }}

      # https://github.com/google-github-actions/setup-gcloud
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@1b47649e585c2bc0808838cec476c8ab6d84f963

      - name: Update google cloud function
        run: |
          bash "${GITHUB_WORKSPACE}/deploy.sh"
```
